language: python
python:
  - '3.4'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3-dev
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - python setup.py install
script:
  - python setup.py test
